### ISSUE TITLE
New version savefiles crashes instant  

### ISSUE THREAD

**Issue by muesli-dev** [ClayAmore/ER-Save-Editor#32]
cant open any savefile created after 19.06.2024 (after the dlc pre patch)

**Comment by LilOhGee** [comment]
I can confirm this is happening on my side too, my backup file from before patch still work.

**Comment by elendil7** [comment]
+1, happening on my end too, instant crash on save file load

**Comment by irxnbxy** [comment]
can i have the file from before patch?

**Comment by jacobthebossie** [comment]
Im on playstation on version 1.0 and i cant edit mine for some reason 
idk why

**Comment by ClayAmore** [comment]
duplicate of #43
