### ISSUE TITLE
Save file editor isnt working

### ISSUE THREAD

**Issue by jacobthebossie** [ClayAmore/ER-Save-Editor#37]
Hey so here's the issue with ER save editor for Elden Ring every time I try and load my  PlayStation save into the editor  it crashes and shuts down the program I'm using a save file from the beginning of the game with no updates at all its super annoying because I can't make any edits to my save data if someone can please tell me what's going on I'd be very grateful.

**Comment by jacobthebossie** [comment]
If someone could please help id be so grateful

**Comment by St0rmDev** [comment]
yes save editor likely not working due to new dlc data needs fix

**Comment by jacobthebossie** [comment]
> yes save editor likely not working due to new dlc data needs fix

Do you have any idea when they will get that fixed because i by accidently removed my save file from last time 😭

**Comment by ClayAmore** [comment]
duplicate of #43
