### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by Ninjafartdust130** [ClayAmore/ER-Save-Editor#39]
Hi is it possible u can make the save editor with the new dlc weapons

**Comment by R0yl** [comment]
Waiting for the update too, for crying out aloud

**Comment by jacobthebossie** [comment]
what do you mean update please i thought you were the dude to make it work???

**Comment by jacobthebossie** [comment]
> Waiting for the update too, for crying out aloud
> 
> 

what update is it for the save editor???

**Comment by Ninjafartdust130** [comment]
Yes I want one for the save editor so we can get dlc weapons

**Comment by jacobthebossie** [comment]
> Yes I want one for the save editor so we can get dlc weapons 

but what if you don't have the dlc can you still use save editor??

**Comment by Ninjafartdust130** [comment]
I think I got dlc weapons from friends

**Comment by jacobthebossie** [comment]
> I think I got dlc weapons from friends

do you have the DLC?

**Comment by Ninjafartdust130** [comment]
I don't no

**Comment by Ninjafartdust130** [comment]
People gave me some though

**Comment by Ninjafartdust130** [comment]
Some dlc weapons

**Comment by jacobthebossie** [comment]
> Some dlc weapons 

do you have any idea when they will update this?

**Comment by Ninjafartdust130** [comment]
No I don't I was asking for one

**Comment by jacobthebossie** [comment]
> No I don't I was asking for one

is your save editor working on console???

**Comment by Ninjafartdust130** [comment]
Yes

**Comment by Ninjafartdust130** [comment]
I use a discord bot that description like save wizard it's free look it up

**Comment by jacobthebossie** [comment]
> I use a discord bot that description like save wizard it's free look it up

do you mind adding me on discord and sending me the link my user is mhmjacob

**Comment by jacobthebossie** [comment]
> I use a discord bot that description like save wizard it's free look it up

also i already have save wizard so i shouldn't need it free it's just that my save editor for elden ring keeps crashing whenever i put in the txt file and it's really bugging me out

**Comment by jacobthebossie** [comment]
im so confused how did you get console to work its not working for me

**Comment by carloslos** [comment]
This is not a forum, don't open useless issues just begging, geeeeeez.

**Comment by Ninjafartdust130** [comment]
Womp womp

**Comment by ClayAmore** [comment]
duplicate of #43
