### ISSUE TITLE
Fix crashing on PS saves

### ISSUE THREAD

**Issue by jacobthebossie** [ClayAmore/ER-Save-Editor#40]
Hey, y'all, I've been dealing with a frustrating situation regarding the Save Editor. It's giving me a hard time by not loading my saves and crashing repeatedly. Could you please investigate this issue and provide a fix? I truly enjoy using the editor to enhance my gaming experience, so it would mean a lot if you could address this hiccup. I appreciate all the effort you put into your work, and I'm hopeful for a speedy resolution to this problem! Your help in resolving this matter would be greatly appreciated, and I look forward to getting back to enjoying the game with the editor's functionality restored. Thanks a bunch for your attention to this matter!

**Comment by jacobthebossie** [comment]
@ClayAmore ?

**Comment by Ninjafartdust130** [comment]
Hey has anyone figured out how to stop saves from crashing

**Comment by jacobthebossie** [comment]
> Hey has anyone figured out how to stop saves from crashing

no nobody is answering me i wish i could dm one of the creators and ask them

**Comment by jacobthebossie** [comment]
I hope they fix this by tomorrow cause i'm not restarting my elden ring😭

**Comment by ghost** [comment]
Guys i have compiled latest version which solves the crash of PS saves.
[DOWNLOAD](https://mega.nz/file/YIYGGKiK#dyZGqOs9_XEYYjsN0aw9cpHOM_MAWzMIy994BSpf-v0)

**Comment by Ninjafartdust130** [comment]
its a virus

**Comment by ghost** [comment]
> its a virus

I just compiled the source code.

**Comment by ClayAmore** [comment]
duplicate of #43
