### ISSUE TITLE
Open error

### ISSUE THREAD

**Issue by Ninjafartdust130** [ClayAmore/ER-Save-Editor#41]
When I use the open save file thing and it crashes

**Comment by jacobthebossie** [comment]
it seems to only be with PS tho the PC doesn't affect the save only the PS4 saves effect it

**Comment by mit999sif** [comment]
It happened to me too, I think is for the DLC.
I use PC, I bought the game with the DLC , now that the DLC has been release the program can't handle.

**Comment by yesdog96** [comment]
From what I heard Steel has a test copy of the update to the editor. Shouldn't be too long before it's updated. On Nexusmods @ClayAmore has said that he's working on the update. If you look at the files here it's been updated yesterday.

**Comment by jacobthebossie** [comment]
> From what I heard Steel has a test copy of the update to the editor. Shouldn't be too long before it's updated. On Nexusmods @ClayAmore has said that he's working on the update. If you look at the files here it's been updated yesterday. 

think it'll be done by tomorrow?

**Comment by yesdog96** [comment]
No idea. Cheat engine tables were just updated partially. Steel has not streamed at all today, so I assume they're either working on it or taking a day off.

**Comment by ClayAmore** [comment]
duplicate of #43

**Comment by ClayAmore** [comment]
duplicate of #43
