### ISSUE TITLE
Keeps crashing when i try open or drag the memory thing 

### ISSUE THREAD

**Issue by Kyaxc** [ClayAmore/ER-Save-Editor#45]
I have decrypted the save I want to use and when I try to drag the memory DAT file or open it in the editor the editor just closes. I also read somewhere tagt if I have more than 5 characters the editor will crash but I have 2 characters so I don't think that is the issue. If I'm doing something wrong please let me know as I could just be stupid

**Comment by BD911-Coder** [comment]
+1

**Comment by ClayAmore** [comment]
duplicate of #43
