### ISSUE TITLE
Feature Resqust: JSON Output Request

### ISSUE THREAD

**Issue by SongTonyLi** [ClayAmore/ER-Save-Editor#68]
I'm truly amazed by this project. Unfortunately, I'm no really familiar with Rust. Is it possible to have a feature that I can get a JSON user's data directly.

**Comment by nozwock** [comment]
Duplicate #59
https://github.com/ClayAmore/ER-Save-Editor/issues/59#issuecomment-2233728183

**Comment by ClayAmore** [comment]
Can this be closed as a duplicate?
