### ISSUE TITLE
Ps4 DLC Save close the Programm

### ISSUE THREAD

**Issue by FunjaPlays** [ClayAmore/ER-Save-Editor#76]
Hey if i try to Open my dlc save file the Programm instantly close 

I hope a future update helps out 

Thx for ur hard work

**Comment by wenjian-zhou** [comment]
You can check out my fork, it works with the save file from [here](https://github.com/ClayAmore/ER-Save-Lib/blob/master/test/PS_Save.txt)

**Comment by FunjaPlays** [comment]
I try it but Programm close after I select the save

**Comment by FunjaPlays** [comment]
I use the exe file of the Programm

**Comment by wenjian-zhou** [comment]
> I use the exe file of the Programm 

Did you use the exe in my fork?

**Comment by FunjaPlays** [comment]
How u got a txt file from the save ?

**Comment by wenjian-zhou** [comment]
> How u got a txt file from the save ?

@FunjaPlays Use the savewizard to export to a txt file, if you are playing on playstation

**Comment by FunjaPlays** [comment]
![image](https://github.com/user-attachments/assets/be697784-9ba3-43c5-8a6c-89f046e1690b)

**Comment by FunjaPlays** [comment]
Got this error if I use my dlc savegame

**Comment by wenjian-zhou** [comment]
Yes, I can't use my save too, but you can use the file I mentioned above

**Comment by ClayAmore** [comment]
@FunjaPlays Can you post the save file so I can look at your items list. I am curious?

**Comment by wenjian-zhou** [comment]
@ClayAmore I can share my save file if you need one more reference. https://drive.google.com/file/d/1vYgLaQL3MrglaS8FkTZxjNvyZEkEZ7sN/view?usp=sharing

**Comment by FunjaPlays** [comment]
@ClayAmore sure https://drive.google.com/file/d/1--pL0h5QlqQcZe4-8bma6FeRsrf6eZhy/view?usp=drivesdk

**Comment by ClayAmore** [comment]
Thank you. I'll fix this bug. It's not recognizing the save as a playstation and trying to parse it as a pc save.

**Comment by ClayAmore** [comment]
I updated the er-save-lib. A fresh build should be able to parse this save now.
![image](https://github.com/user-attachments/assets/cda983b9-4146-48db-9ef0-eb5d18a50f23)

**Comment by FunjaPlays** [comment]
Thx bud 
I try it if I'm back home 
I hope I can edit my savefile with that

**Comment by wenjian-zhou** [comment]
@ClayAmore how to build it? Is it the same as ER-Save-Editor?

**Comment by wenjian-zhou** [comment]
how to build it? Is it the same as ER-Save-Editor? If I build the lib, how should I use it with the save editor? @ClayAmore

**Comment by wenjian-zhou** [comment]
nvm, I managed to build it, it turned out that

`
[[package]]  
name = "er-save-lib"  
version = "0.1.0"  
source = "git+https://github.com/ClayAmore/ER-Save-Lib.git#2753ac0a0734d2d5e9f87e803ef83c34b473792c"
`

which is in `Cargo.lock` is preventing cargo to update the er-save-lib, so I changed it to:

`
[[package]]
name = "er-save-lib"  
version = "0.1.0"  
source = "git+https://github.com/ClayAmore/ER-Save-Lib.git"
`

**Comment by wenjian-zhou** [comment]
@FunjaPlays I have the latest build in my fork now, it works find with my save.

**Comment by ClayAmore** [comment]
Nice!
